# 服务器配置
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

# spring相关配置
spring:
  # 自定义多数据源，不自动装载DataSource
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  # i18n资源文件配置，供thymeleaf读取
  messages:
    # 这个basename非常之坑，必须要配到目录+文件名通用前缀
    #如文件名为demo_zh_CN.properties则配置为i18n/messages/demo
    basename: i18n/messages/global
    encoding: UTF-8

  # 数据源配置
#  datasource:
#    url: jdbc:mysql://localhost:3306/dev?serverTimezone=GMT&characterEncoding=utf-8
#    username: orange
#    password: orange
#    driver-class-name: com.mysql.cj.jdbc.Driver
##    driver-class-name: oracle.jdbc.driver.OracleDriver
#    type: com.alibaba.druid.pool.DruidDataSource
#    dbcp2:
#      initial-size: 1
#      min-idle: 1
#      max-idle: 10
#      test-while-idle: true
#      max-wait-millis: 6000
#      validation-query: SELECT 'X'
  datasource:
    primary-db:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: orange
      password: orange
      # SpringBoot原生DHCP配置
#      jdbc-url: jdbc:mysql://localhost:3306/dev?serverTimezone=GMT&characterEncoding=utf-8&allowMultiQueries=true
      # Druid 配置
      url: jdbc:mysql://localhost:3306/dev?serverTimezone=GMT&characterEncoding=utf-8&allowMultiQueries=true
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 2
      minIdle: 2
      maxActive: 10
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
    test-db:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: orange
      password: orange
       # SpringBoot原生DHCP配置
#      jdbc-url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT&characterEncoding=utf-8&allowMultiQueries=true
      # Druid 配置
      url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT&characterEncoding=utf-8&allowMultiQueries=true
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 2
      minIdle: 2
      maxActive: 10
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20




  # thymeleaf模板配置
  thymeleaf:
    prefix: classpath:pages/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  # 热部署配置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources

  # 静态资源配置
  mvc:
    static-path-pattern: /static/**

  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

# mybatis配置
mybatis:
  type-aliases-package: com.orange.basetool.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: false
    local-cache-scope: statement
    #当查询数据为空时字段返回为null，不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    default-fetch-size: 20
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志相关配置
logging:
  config: classpath:logback.xml
  file: basetool.log
  path: E:\WorkSpaces\IDEA\basetool
  level:
    com:
      orange:
        basetool:
          mapper: debug


